#!/usr/bin/env bash
#
#	etcd OCF RA.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#

#######################################################################

# Initialization:

: "${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}"
. "${OCF_FUNCTIONS_DIR}/ocf-shellfuncs"

#
# These are the defaults for the tunables that are availble in etcd
#

OCF_RESKEY_name_default="default"
OCF_RESKEY_data_dir_default="default.etcd"
OCF_RESKEY_wal_dir_default=""
OCF_RESKEY_snapshot_count_default="100000"
OCF_RESKEY_heartbeat_interval_default="100"
OCF_RESKEY_election_timeout_default="1000"
OCF_RESKEY_initial_election_tick_advance_default="true"
OCF_RESKEY_listen_peer_urls_default="http://localhost:2380"
OCF_RESKEY_listen_client_urls_default="http://localhost:2379"
OCF_RESKEY_max_snapshots_default="5"
OCF_RESKEY_max_wals_default="5"
OCF_RESKEY_cors_default=""
OCF_RESKEY_quota_backend_bytes_default="0"
OCF_RESKEY_backend_batch_limit_default="0"
OCF_RESKEY_backend_bbolt_freelist_type_default="map"
OCF_RESKEY_backend_batch_interval_default="0"
OCF_RESKEY_max_txn_ops_default="128"
OCF_RESKEY_max_request_bytes_default="1572864"
OCF_RESKEY_grpc_keepalive_min_time_default="5s"
OCF_RESKEY_grpc_keepalive_interval_default="2h"
OCF_RESKEY_grpc_keepalive_timeout_default="20s"
OCF_RESKEY_initial_advertise_peer_urls_default="http://localhost:2380"
OCF_RESKEY_initial_cluster_default="http://localhost:2380"
OCF_RESKEY_initial_cluster_state_default="new"
OCF_RESKEY_initial_cluster_token_default="etcd_cluster"
OCF_RESKEY_advertise_client_urls_default="http://localhost:2379"
OCF_RESKEY_discovery_default=""
OCF_RESKEY_discovery_srv_default=""
OCF_RESKEY_discovery_name_default=""
OCF_RESKEY_discovery_fallback_default="proxy"
OCF_RESKEY_discovery_proxy_default=""
OCF_RESKEY_strict_reconfig_check_default="true"
OCF_RESKEY_auto_compaction_retention_default="0"
OCF_RESKEY_auto_compaction_mode_default="periodic"
OCF_RESKEY_enable_v2_default="true"
OCF_RESKEY_proxy_default="off"
OCF_RESKEY_proxy_failure_wait_default="5000"
OCF_RESKEY_proxy_refresh_interval_default="30000"
OCF_RESKEY_proxy_dial_timeout_default="1000"
OCF_RESKEY_proxy_write_timeout_default="5000"
OCF_RESKEY_proxy_read_timeout_default="0"
OCF_RESKEY_cert_file_default=""
OCF_RESKEY_key_file_default=""
OCF_RESKEY_client_cert_auth_default="false"
OCF_RESKEY_client_crl_file_default=""
OCF_RESKEY_client_cert_allowed_hostname_default=""
OCF_RESKEY_trusted_ca_file_default=""
OCF_RESKEY_auto_tls_default="false"
OCF_RESKEY_peer_cert_file_default=""
OCF_RESKEY_peer_key_file_default=""
OCF_RESKEY_peer_client_cert_auth_default="false"
OCF_RESKEY_peer_crl_file_default=""
OCF_RESKEY_peer_trusted_ca_file_default=""
OCF_RESKEY_peer_auto_tls_default="false"
OCF_RESKEY_peer_cert_allowed_cn_default=""
OCF_RESKEY_peer_cert_allowed_hostname_default=""
OCF_RESKEY_cipher_suites_default=""
OCF_RESKEY_logger_default="capnslog"
OCF_RESKEY_log_outputs_default="default"
OCF_RESKEY_log_level_default="info"
OCF_RESKEY_force_new_cluster_default="false"
OCF_RESKEY_version_default="false"
OCF_RESKEY_config_file_default=""
OCF_RESKEY_enable_pprof_default="false"
OCF_RESKEY_metrics_default="basic"
OCF_RESKEY_listen_metrics_urls_default=""
OCF_RESKEY_auth_token_default="simple"
OCF_RESKEY_bcrypt_cost_default="10"
OCF_RESKEY_user_default="etcd"
OCF_RESKEY_group_default="etcd"
OCF_RESKEY_pid_file_default="/var/run/etcd/etcd.pid"

: ${OCF_RESKEY_name="${OCF_RESKEY_name_default}"}
: ${OCF_RESKEY_data_dir="${OCF_RESKEY_data_dir_default}"}
: ${OCF_RESKEY_wal_dir="${OCF_RESKEY_wal_dir_default}"}
: ${OCF_RESKEY_snapshot_count="${OCF_RESKEY_snapshot_count_default}"}
: ${OCF_RESKEY_heartbeat_interval="${OCF_RESKEY_heartbeat_interval_default}"}
: ${OCF_RESKEY_election_timeout="${OCF_RESKEY_election_timeout_default}"}
: ${OCF_RESKEY_initial_election_tick_advance="${OCF_RESKEY_initial_election_tick_advance_default}"}
: ${OCF_RESKEY_listen_peer_urls="${OCF_RESKEY_listen_peer_urls_default}"}
: ${OCF_RESKEY_listen_client_urls="${OCF_RESKEY_listen_client_urls_default}"}
: ${OCF_RESKEY_max_snapshots="${OCF_RESKEY_max_snapshots_default}"}
: ${OCF_RESKEY_max_wals="${OCF_RESKEY_max_wals_default}"}
: ${OCF_RESKEY_cors="${OCF_RESKEY_cors_default}"}
: ${OCF_RESKEY_quota_backend_bytes="${OCF_RESKEY_quota_backend_bytes_default}"}
: ${OCF_RESKEY_backend_batch_limit="${OCF_RESKEY_backend_batch_limit_default}"}
: ${OCF_RESKEY_backend_bbolt_freelist_type="${OCF_RESKEY_backend_bbolt_freelist_type_default}"}
: ${OCF_RESKEY_backend_batch_interval="${OCF_RESKEY_backend_batch_interval_default}"}
: ${OCF_RESKEY_max_txn_ops="${OCF_RESKEY_max_txn_ops_default}"}
: ${OCF_RESKEY_max_request_bytes="${OCF_RESKEY_max_request_bytes_default}"}
: ${OCF_RESKEY_grpc_keepalive_min_time="${OCF_RESKEY_grpc_keepalive_min_time_default}"}
: ${OCF_RESKEY_grpc_keepalive_interval="${OCF_RESKEY_grpc_keepalive_interval_default}"}
: ${OCF_RESKEY_grpc_keepalive_timeout="${OCF_RESKEY_grpc_keepalive_timeout_default}"}
: ${OCF_RESKEY_initial_advertise_peer_urls="${OCF_RESKEY_initial_advertise_peer_urls_default}"}
: ${OCF_RESKEY_initial_cluster="${OCF_RESKEY_initial_cluster_default}"}
: ${OCF_RESKEY_initial_cluster_state="${OCF_RESKEY_initial_cluster_state_default}"}
: ${OCF_RESKEY_initial_cluster_token="${OCF_RESKEY_initial_cluster_token_default}"}
: ${OCF_RESKEY_advertise_client_urls="${OCF_RESKEY_advertise_client_urls_default}"}
: ${OCF_RESKEY_discovery="${OCF_RESKEY_discovery_default}"}
: ${OCF_RESKEY_discovery_srv="${OCF_RESKEY_discovery_srv_default}"}
: ${OCF_RESKEY_discovery_name="${OCF_RESKEY_discovery_name_default}"}
: ${OCF_RESKEY_discovery_fallback="${OCF_RESKEY_discovery_fallback_default}"}
: ${OCF_RESKEY_discovery_proxy="${OCF_RESKEY_discovery_proxy_default}"}
: ${OCF_RESKEY_strict_reconfig_check="${OCF_RESKEY_strict_reconfig_check_default}"}
: ${OCF_RESKEY_auto_compaction_retention="${OCF_RESKEY_auto_compaction_retention_default}"}
: ${OCF_RESKEY_auto_compaction_mode="${OCF_RESKEY_auto_compaction_mode_default}"}
: ${OCF_RESKEY_enable_v2="${OCF_RESKEY_enable_v2_default}"}
: ${OCF_RESKEY_proxy="${OCF_RESKEY_proxy_default}"}
: ${OCF_RESKEY_proxy_failure_wait="${OCF_RESKEY_proxy_failure_wait_default}"}
: ${OCF_RESKEY_proxy_refresh_interval="${OCF_RESKEY_proxy_refresh_interval_default}"}
: ${OCF_RESKEY_proxy_dial_timeout="${OCF_RESKEY_proxy_dial_timeout_default}"}
: ${OCF_RESKEY_proxy_write_timeout="${OCF_RESKEY_proxy_write_timeout_default}"}
: ${OCF_RESKEY_proxy_read_timeout="${OCF_RESKEY_proxy_read_timeout_default}"}
: ${OCF_RESKEY_cert_file="${OCF_RESKEY_cert_file_default}"}
: ${OCF_RESKEY_key_file="${OCF_RESKEY_key_file_default}"}
: ${OCF_RESKEY_client_cert_auth="${OCF_RESKEY_client_cert_auth_default}"}
: ${OCF_RESKEY_client_crl_file="${OCF_RESKEY_client_crl_file_default}"}
: ${OCF_RESKEY_client_cert_allowed_hostname="${OCF_RESKEY_client_cert_allowed_hostname_default}"}
: ${OCF_RESKEY_trusted_ca_file="${OCF_RESKEY_trusted_ca_file_default}"}
: ${OCF_RESKEY_auto_tls="${OCF_RESKEY_auto_tls_default}"}
: ${OCF_RESKEY_peer_cert_file="${OCF_RESKEY_peer_cert_file_default}"}
: ${OCF_RESKEY_peer_key_file="${OCF_RESKEY_peer_key_file_default}"}
: ${OCF_RESKEY_peer_client_cert_auth="${OCF_RESKEY_peer_client_cert_auth_default}"}
: ${OCF_RESKEY_peer_crl_file="${OCF_RESKEY_peer_crl_file_default}"}
: ${OCF_RESKEY_peer_trusted_ca_file="${OCF_RESKEY_peer_trusted_ca_file_default}"}
: ${OCF_RESKEY_peer_auto_tls="${OCF_RESKEY_peer_auto_tls_default}"}
: ${OCF_RESKEY_peer_cert_allowed_cn="${OCF_RESKEY_peer_cert_allowed_cn_default}"}
: ${OCF_RESKEY_peer_cert_allowed_hostname="${OCF_RESKEY_peer_cert_allowed_hostname_default}"}
: ${OCF_RESKEY_cipher_suites="${OCF_RESKEY_cipher_suites_default}"}
: ${OCF_RESKEY_logger="${OCF_RESKEY_logger_default}"}
: ${OCF_RESKEY_log_outputs="${OCF_RESKEY_log_outputs_default}"}
: ${OCF_RESKEY_log_level="${OCF_RESKEY_log_level_default}"}
: ${OCF_RESKEY_force_new_cluster="${OCF_RESKEY_force_new_cluster_default}"}
: ${OCF_RESKEY_version="${OCF_RESKEY_version_default}"}
: ${OCF_RESKEY_config_file="${OCF_RESKEY_config_file_default}"}
: ${OCF_RESKEY_enable_pprof="${OCF_RESKEY_enable_pprof_default}"}
: ${OCF_RESKEY_metrics="${OCF_RESKEY_metrics_default}"}
: ${OCF_RESKEY_listen_metrics_urls="${OCF_RESKEY_listen_metrics_urls_default}"}
: ${OCF_RESKEY_auth_token="${OCF_RESKEY_auth_token_default}"}
: ${OCF_RESKEY_bcrypt_cost="${OCF_RESKEY_bcrypt_cost_default}"}
: ${OCF_RESKEY_user="${OCF_RESKEY_user_default}"}
: ${OCF_RESKEY_group="${OCF_RESKEY_group_default}"}
: ${OCF_RESKEY_pid_file="${OCF_RESKEY_pid_file_default}"}

######################################################################

# Use runuser if available for SELinux.
if [ -x /sbin/runuser ]; then
  SU=runuser
else
  SU=su
fi

make_etcd_arguments() {
  #
  # This method takes all of the final env vars and builds a cmdline
  # argument list based on this
  #
  ALL_ENV=()

  while IFS= read -r line; do
    ALL_ENV+=("${line}")
  done <<<"$(set | grep -E "^OCF_RESKEY_" | grep -Evi "CRM_" | grep -Ev "default=")"

  BLACKLIST=(
    "pid-file="
    "user="
    "group="
    "CRM"
  )

  declare ARG_LIST=()

  for arg in "${ALL_ENV[@]}"; do
    varname=${arg%%=*}
    if [[ "${arg}" =~ ^OCF_RESKEY_([^=]+)=([^=]+)$ ]]; then
      shortenvvar=${BASH_REMATCH[1]}
      etcdopt=${shortenvvar//_/-}
      etcdarg=${BASH_REMATCH[2]}
      [[ "${BLACKLIST[*]}" =~ ${shortenvvar} ]] && continue
      defname="${varname}_default"
      if [[ "${!varname}" != "${!defname}" ]]; then
        >&2 echo "${varname} is not default"
        [[ "${etcdarg}" =~ ^[0-9]+$ ]] && : # etcdarg=$(printf "%q" ${etcdarg})
        ARG_LIST+=("$(printf " --%q=%s" ${etcdopt} ${etcdarg})")
        unset "${varname}"
      fi
    fi
  done

  >&2 echo "${ARG_LIST[@]}"

  echo "${ARG_LIST[@]}"

  return
}

meta_data() {
  cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="etcd">
  <version>1.0</version>

  <longdesc lang="en">
This is the etcd Resource Agent. It starts, stops, and monitors
etcd for failures.
  </longdesc>
  <shortdesc lang="en">etcd resource agent</shortdesc>
  <parameters>
    <parameter name="name" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_name_default}" />
    </parameter>
    <parameter name="data_dir" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_data_dir_default}" />
    </parameter>
    <parameter name="wal_dir" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_wal_dir_default}" />
    </parameter>
    <parameter name="snapshot_count" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_snapshot_count_default}" />
    </parameter>
    <parameter name="heartbeat_interval" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_heartbeat_interval_default}" />
    </parameter>
    <parameter name="election_timeout" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_election_timeout_default}" />
    </parameter>
    <parameter name="initial_election_tick_advance" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_initial_election_tick_advance_default}" />
    </parameter>
    <parameter name="listen_peer_urls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_listen_peer_urls_default}" />
    </parameter>
    <parameter name="listen_client_urls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_listen_client_urls_default}" />
    </parameter>
    <parameter name="max_snapshots" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_max_snapshots_default}" />
    </parameter>
    <parameter name="max_wals" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_max_wals_default}" />
    </parameter>
    <parameter name="cors" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_cors_default}" />
    </parameter>
    <parameter name="quota_backend_bytes" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_quota_backend_bytes_default}" />
    </parameter>
    <parameter name="backend_batch_limit" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_backend_batch_limit_default}" />
    </parameter>
    <parameter name="backend_bbolt_freelist_type" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_backend_bbolt_freelist_type_default}" />
    </parameter>
    <parameter name="backend_batch_interval" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_backend_batch_interval_default}" />
    </parameter>
    <parameter name="max_txn_ops" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_max_txn_ops_default}" />
    </parameter>
    <parameter name="max_request_bytes" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_max_request_bytes_default}" />
    </parameter>
    <parameter name="grpc_keepalive_min_time" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_grpc_keepalive_min_time_default}" />
    </parameter>
    <parameter name="grpc_keepalive_interval" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_grpc_keepalive_interval_default}" />
    </parameter>
    <parameter name="grpc_keepalive_timeout" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_grpc_keepalive_timeout_default}" />
    </parameter>
    <parameter name="initial_advertise_peer_urls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_initial_advertise_peer_urls_default}" />
    </parameter>
    <parameter name="initial_cluster" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_initial_cluster_default}" />
    </parameter>
    <parameter name="initial_cluster_state" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_initial_cluster_state_default}" />
    </parameter>
    <parameter name="initial_cluster_token" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_initial_cluster_token_default}" />
    </parameter>
    <parameter name="advertise_client_urls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_advertise_client_urls_default}" />
    </parameter>
    <parameter name="discovery" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_discovery_default}" />
    </parameter>
    <parameter name="discovery_srv" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_discovery_srv_default}" />
    </parameter>
    <parameter name="discovery_name" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_discovery_name_default}" />
    </parameter>
    <parameter name="discovery_fallback" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_discovery_fallback_default}" />
    </parameter>
    <parameter name="discovery_proxy" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_discovery_proxy_default}" />
    </parameter>
    <parameter name="strict_reconfig_check" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_strict_reconfig_check_default}" />
    </parameter>
    <parameter name="auto_compaction_retention" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_auto_compaction_retention_default}" />
    </parameter>
    <parameter name="auto_compaction_mode" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_auto_compaction_mode_default}" />
    </parameter>
    <parameter name="enable_v2" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_enable_v2_default}" />
    </parameter>
    <parameter name="proxy" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_default}" />
    </parameter>
    <parameter name="proxy_failure_wait" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_failure_wait_default}" />
    </parameter>
    <parameter name="proxy_refresh_interval" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_refresh_interval_default}" />
    </parameter>
    <parameter name="proxy_dial_timeout" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_dial_timeout_default}" />
    </parameter>
    <parameter name="proxy_write_timeout" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_write_timeout_default}" />
    </parameter>
    <parameter name="proxy_read_timeout" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_proxy_read_timeout_default}" />
    </parameter>
    <parameter name="cert_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_cert_file_default}" />
    </parameter>
    <parameter name="key_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_key_file_default}" />
    </parameter>
    <parameter name="client_cert_auth" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_client_cert_auth_default}" />
    </parameter>
    <parameter name="client_crl_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_client_crl_file_default}" />
    </parameter>
    <parameter name="client_cert_allowed_hostname" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_client_cert_allowed_hostname_default}" />
    </parameter>
    <parameter name="trusted_ca_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_trusted_ca_file_default}" />
    </parameter>
    <parameter name="auto_tls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_auto_tls_default}" />
    </parameter>
    <parameter name="peer_cert_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_cert_file_default}" />
    </parameter>
    <parameter name="peer_key_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_key_file_default}" />
    </parameter>
    <parameter name="peer_client_cert_auth" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_client_cert_auth_default}" />
    </parameter>
    <parameter name="peer_crl_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_crl_file_default}" />
    </parameter>
    <parameter name="peer_trusted_ca_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_trusted_ca_file_default}" />
    </parameter>
    <parameter name="peer_auto_tls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_auto_tls_default}" />
    </parameter>
    <parameter name="peer_cert_allowed_cn" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_cert_allowed_cn_default}" />
    </parameter>
    <parameter name="peer_cert_allowed_hostname" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_peer_cert_allowed_hostname_default}" />
    </parameter>
    <parameter name="cipher_suites" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_cipher_suites_default}" />
    </parameter>
    <parameter name="logger" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_logger_default}" />
    </parameter>
    <parameter name="log_outputs" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_log_outputs_default}" />
    </parameter>
    <parameter name="log_level" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_log_level_default}" />
    </parameter>
    <parameter name="force_new_cluster" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_force_new_cluster_default}" />
    </parameter>
    <parameter name="version" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_version_default}" />
    </parameter>
    <parameter name="config_file" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_config_file_default}" />
    </parameter>
    <parameter name="enable_pprof" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_enable_pprof_default}" />
    </parameter>
    <parameter name="metrics" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_metrics_default}" />
    </parameter>
    <parameter name="listen_metrics_urls" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_listen_metrics_urls_default}" />
    </parameter>
    <parameter name="auth_token" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_auth_token_default}" />
    </parameter>
    <parameter name="bcrypt_cost" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_bcrypt_cost_default}" />
    </parameter>
    <parameter name="user" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_user_default}" />
    </parameter>
    <parameter name="group" unique="0" required="0">
      <content type="string" default="${OCF_RESKEY_group_default}" />
    </parameter>
  </parameters>

  <actions>
    <action name="start"        timeout="20s" />
    <action name="stop"         timeout="20s" />
    <action name="monitor"      timeout="20s" interval="10s" depth="0" />
    <action name="reload"       timeout="20s" />
    <action name="meta-data"    timeout="5s" />
    <action name="validate-all"   timeout="20s" />
  </actions>
</resource-agent>
END
}

#######################################################################

etcd_pid() {
  local pid=""

  #pid=$(pidof /usr/local/sbin/etcd)
  pid=$(pgrep -u etcd -f /usr/local/sbin/etcd)

  if [[ "$?" == "0" ]] && (echo "${pid}" | grep -E "^[0-9]+$" >/dev/null 2>&1); then
    printf "%d\n" "${pid}"
    return 0
  else
    printf "%d" 0
    return 1
  fi
}

etcd_kill() {
  local PIDS=()
  if [ "$#" == "0" ]; then
    # No args?
    return 1
  fi

  while (("$#")); do
    PIDS+=("$1")
    shift
  done

  for pid in "${PIDS[@]}"; do
    ocf_log info "Killing pid ${pid}"
    kill -s 15 "${pid}" || {
      ocf_log warn "Error killing pid ${pid} - $?"
      return "$OCF_ERR_GENERIC"
    }
  done

  sleep 5

  for pid in "${PIDS[@]}"; do
    ps -p "${pid}" >/dev/null 2>&1

    if [ "$?" == "0" ]; then
      ocf_log error "Unable to kill pid ${pid}"
      return "$OCF_ERR_GENERIC"
    else
      ocf_log info "PID ${pid} has been killed with SIGTERM"
    fi
  done

  return 0
}

#
#   Run the given command in the Resource owner environment...
#
etcd_runasowner() {
  cmd="${SU} -u "${OCF_RESKEY_user}" -g "${OCF_RESKEY_group}" -- \
      /usr/local/sbin/daemonize -p "${OCF_RESKEY_pid_file}" -a -e \
      /var/lib/etcd/error.log -o /var/lib/etcd/console.log /usr/local/sbin/etcd"

  for arg in "$@"; do
    cmd="${cmd} ${arg}"
  done

  echo "Command: ${cmd}"

  ${cmd} 2>&1

  return $?
}

etcd_usage() {
  cat <<END
usage: $0 {start|stop|monitor|migrate_to|migrate_from|validate-all|meta-data}
END
}

etcd_start() {
  local potential_pid

  set -x

  ETCD_ARGS=($(make_etcd_arguments))

  if [[ -f "${OCF_RESKEY_pid_file}" ]]; then
    potential_pid=$(cat "${OCF_RESKEY_pid_file}")

    if [ "$?" != "0" ]; then
      ocf_log error "Unable to read pid file ${OCF_RESKEY_pid_file}, exiting"
      return "$OCF_ER_GENERIC"
    fi

    if [ "${potential_pid}" == "0" ]; then
      ocf_log warn "Strange anomaly, etcd pid file contains pid 0, deleting"
      rm -rf "${OCF_RESKEY_pid_file}"
    else
      kill -s 0 "${potential_pid}" >/dev/null 2>&1

      if [ "$?" == "0" ]; then
        ocf_log error "PID file ${OCF_RESKEY_pid_file} exists and is running.  Refusing to start"
        return "$OCF_ERR_GENERIC"
      else
        ocf_log error "PID file ${OCF_RESKEY_pid_file} exists but it stale.  Removing"
        rm -f "${OCF_RESKEY_pid_file}"
      fi
    fi
  fi

  #
  # And go!
  #
  etcd_runasowner ${ETCD_ARGS[@]}

  PID=$(etcd_pid)

  if [[ ! "${PID}" ]] || [[ ! "${PID}" =~ ^[0-9]+$ ]]; then
    ocf_log error "Unable to start etcd"
    return "$OCF_ERR_GENERIC"
  fi

  echo "${PID}" >"${OCF_RESKEY_pid_file}" || {
    ocf_log error "Unable to write pidfile ${OCF_RESKEY_pid_file}"
    return "$OCF_ERR_GENERIC"
  }

  return "$OCF_SUCCESS"
}

etcd_stop() {
  if [[ ! -f "${OCF_RESKEY_pid_file}" ]]; then
    PID=$(etcd_pid)
    if [ "$?" != "0" ]; then
      ocf_log info "ETCD is not running on this node, cannot stop"
      return "$OCF_SUCCESS"
    else
      ocf_log error "ETCD is running on this node but has no pid file"
      etcd_kill "${PID}" || {
        ocf_log info "ETCD is refusing to die!"
        return "$OCF_ERR_GENERIC"
      }
      return "$OCF_SUCCESS"
    fi
  else
    pidfile_pid=$(cat "${OCF_RESKEY_pid_file}")

    PID=$(etcd_pid)

    if [[ "${PID}" == "0" ]]; then
      ocf_log info "ETCD was running but is now not!"
      rm -f "${OCF_RESKEY_pid_file}" >/dev/null 2>&1
      return "$OCF_SUCCESS"
    elif [[ "${PID}" != "${pidfile_pid}" ]]; then
      ocf_log warn "Pid file and pidof report different pids!"

      etcd_kill "${PID}" "${pidfile_pid}" && {
        rm -f "${OCF_RESKEY_pid_file}"
        ocf_log info "Successfully shut down ETCD"
        return "$OCF_SUCCESS"
      } || {
        ocf_log error "Unable to kill pid ${PID} and/or ${pidfile_pid}"
        return "$OCF_ERR_GENERIC"
      }
    else
      etcd_kill "${PID}" && {
        rm -f "${OCF_RESKEY_pid_file}"
        ocf_log info "Successfully shut down ETCD"
        return "$OCF_SUCCESS"
      } || {
        ocf_log error "Unable to shut down ETCD"
        return "$OCF_ERR_GENERIC"
      }
    fi
  fi
}

etcd_monitor() {
  # Monitor _MUST!_ differentiate correctly between running
  # (SUCCESS), failed (ERROR) or _cleanly_ stopped (NOT RUNNING).
  # That is THREE states, not just yes/no.

  if [[ ! -f "${OCF_RESKEY_pid_file}" ]]; then
    etcd_pid && {
      ocf_log warn "ETCD running with no pid file!"
      return "$OCF_ERR_GENERIC"
    }

    return "$OCF_NOT_RUNNING"
  fi

  actualpid=$(etcd_pid) || {
    ocf_log error "Unable to identify running etcd"
    return "$OCF_ERR_GENERIC"
  }

  filepid=$(cat "${OCF_RESKEY_pid_file}") || {
    ocf_log warn "Unable to get pid from file"
    return "$OCF_ERR_GENERIC"
  }

  if [[ "${filepid}" != "${actualpid}" ]]; then
    ocf_log warn "ETCD is running however it is not the pid referenced in the pidfile"
    return "$OCF_ERR_GENERIC"
  fi

  kill -s 0 $(cat "${OCF_RESKEY_pid_file}") >/dev/null 2>&1 || {
    ocf_log error "Pid file ${OCF_RESKEY_pid_file} exists but pid is not running"
    return "$OCF_ERR_GENERIC"
  }

  ETCDCTL_API=3 /usr/local/bin/etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt \
    --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key \
    member list || {
    ocf_log error "Unable to query etcd at https://[127.0.0.1]:2379"
    return "$OCF_ERR_GENERIC"
  }

  return "$OCF_SUCCESS"
}

etcd_validate() {
  return "$OCF_SUCCESS"
}

#
# Make Pidfile Dir
#

piddir="${OCF_RESKEY_pid_file%/etcd.pid}"

output=$(ls -ldZ "${piddir}" 2>&1)
# && ocf_log info "Listing of etcd pid dir: ${output}"

output=$(mkdir -p "${piddir}" 2>&1)
# || ocf_log warn "Cannot mkdir -p ${piddir}: ${output}"

output=$(chown "${OCF_RESKEY_user}":"${OCF_RESKEY_group}" "${piddir}" 2>&1)
# || ocf_log warn "Cannot chown ${OCF_RESKEY_user}:${OCF_RESKEY_group} ${piddir}: ${output}"

output=$(chmod 770 ${piddir} 2>&1)
# || ocf_log warn "Cannot chmod 770 ${piddir}: ${output}"

#
# Then we determine the arguments
#
case "$__OCF_ACTION" in
meta-data)
  meta_data
  exit "$OCF_SUCCESS"
  ;;
start)
  ocf_log info "Starting ${OCF_RESOURCE_INSTANCE}."
  etcd_start
  exit $?
  ;;
stop)
  ocf_log info "Stopping ${OCF_RESOURCE_INSTANCE}."
  etcd_stop
  exit $?
  ;;
monitor)
  etcd_monitor
  ;;
reload)
  ocf_log info "Reloading ${OCF_RESOURCE_INSTANCE} ..."
  etcd_stop
  sleep 5
  etcd_start
  exit $?
  ;;
validate-all)
  etcd_validate
  ;;
usage | help)
  etcd_usage
  exit "$OCF_SUCCESS"
  ;;
migrate_to)
  ocf_log info "Prepping to stop ${OCF_RESOURCE_INSTANCE} for migration"
  return "$OCF_SUCCESS"
  ;;
migrate_from)
  ocf_log info "Prepping to start ${OCF_RESOURCE_INSTANCE} after migration"
  return "$OCF_SUCCESS"
  etcd_start
  ;;
*)
  etcd_usage
  exit "$OCF_ERR_UNIMPLEMENTED"
  ;;
esac
rc=$?
ocf_log debug "${OCF_RESOURCE_INSTANCE} $__OCF_ACTION : $rc"
exit $rc
